### ISSUE TITLE
Update name

### ISSUE THREAD

**Issue by hayleyavw** [uccser/verto#150]
The name has finally been chosen! Which means all references to "Kordac" need to changed to "Verto".

This includes:

- Docs
- File names
- Docstrings
- Repo

**Comment by ravenmaster001** [comment]
Wow cannot do anything right at the moment :(

**Comment by ravenmaster001** [comment]
TODO:
- [ ] Update Logo
- [ ] Update ReadTheDocs
- [ ] Update CodeClimate
- [ ] Update Travis
- [ ] Update GitHub Repo
