### ISSUE TITLE
HTML Parsing - Unclosed tag error

### ISSUE THREAD

**Issue by ravenmaster001** [uccser/verto#168]
This error is produced by HTML void elements that etree expects to be closed due to only being able to parse strings as XML.

**Comment by JackMorganNZ** [comment]
Is there anything we can do as authors to avoid this at the moment?

**Comment by ravenmaster001** [comment]
Other than not use images in panels and boxed-text, no. There also doesn't appear to be any good and quick fix for this will likely take me a day or too.
