### ISSUE TITLE
Update panel tag

### ISSUE THREAD

**Issue by hayleyavw** [uccser/verto#240]
To make creating/editing/translating panel text more user friendly, the following change needs to be implemented:
Currently a panel looks like this:
```
{panel type="teacher-note" title="Teacher Note" subtitle="Curriculum guides for Algorithms"}

This text is the panel's contents.

{panel end}
```
And will be changed to:
```
{panel type="teacher-note" subtitle="true"}

# Teacher Note

## Curriculum guides for Algorithms

This text is the panel's contents.

{panel end}
```
Where the subtitle is the first second level heading only if `subtitle` is `true`.

**Comment by JackMorganNZ** [comment]
It would be good to document why this has changed in the documentation.

**Comment by hayleyavw** [comment]
@JackMorganNZ absolutely, have even included the `documentation` tag to remind myself :)
