### ISSUE TITLE
Add Django i18n support to Kordac output

### ISSUE THREAD

**Issue by JackMorganNZ** [uccser/verto#63]
Some HTML output by Kordac contains words/variables that should be translated. Examples of this is the word `Source` on image output, and panel title's.

To add internationalisation support to Kordac, it's likely we will need to add the following:

1. `{{ trans }}` Django template tags to HTML templates.
2. Add basic Kordac translation file to be included in Django locale folder.
3. Add supporting documentation.

**Comment by ravenmaster001** [comment]
We believe this should be solved by custom html-templates. Putting in future for later verification.

**Comment by JackMorganNZ** [comment]
This is solved by the custom HTML templates. However it does require the tag and it's parameters to be written in English. Possibly could open a new issue for this in the future, however it is not required now.
